# Generated by Django 5.0.3 on 2024-04-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='website_header',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
